### ISSUE TITLE
Please add a README in the root of the repository

### ISSUE THREAD

**Issue by rubendibattista** [skyward-er/msa-toolkit#9]
The `README`  in the root of the repository is the entry point for people reaching this repository from the web and it's important to promote visibility. 

You recently refactored the folder, now there's not a README anymore. Please fix that. :)

**Comment by filippoinno1994** [comment]
yes, we know
we're restoring also the documentation and the readmes as well
be patient

**Comment by rubendibattista** [comment]
Also please keep the affiliation of people that previously worked on the code.
